// Generated by CoffeeScript 1.8.0
Epicport.Canvas = (function() {
  function Canvas(options) {
    var clickToStart;
    this.overlay = $('.canvas_overlay');
    this.canvas = document.getElementById("canvas");
    clickToStart = $('.click_to_start');
    clickToStart.click((function(_this) {
      return function() {
        clickToStart.hide();
        $('.loader').css('display', 'table-cell');
        return options.start();
      };
    })(this));
  }

  Canvas.prototype.el = function() {
    return this.canvas;
  };

  Canvas.prototype.hideOverlay = function() {
    return this.overlay.hide();
  };

  return Canvas;

})();
