// Generated by CoffeeScript 1.8.0
Epicport.modalMessage = function(title, message, callback) {
  var div;
  div = $('<div title="' + title + '">' + message + '</div>');
  return div.dialog({
    appendTo: ".game",
    dialogClass: "modal",
    modal: true,
    draggable: false,
    resizeable: false,
    closeText: "",
    buttons: {
      'Ok': function() {
        $(this).dialog('close');
        if (callback) {
          return callback($(this));
        }
      }
    }
  });
};

Epicport.modalProgress = function() {
  var div;
  div = $('<div class="progress_modal"></div>');
  var game = jQuery(".game");
  $(game).append(div);
  return function() {
    return div.remove();
  };
};
